### ISSUE TITLE
in the new update I get a ticking error if i use this mod

### ISSUE THREAD

**Issue by Worgrick** [genandnic/Wall-Jump#12]
my character is the ticking entity. if you could fix this in your next update i would appreciate it. i can back to you with info if you know what you need.

**Comment by Worgrick** [comment]
the ticking error crashes the game

**Comment by genandnic** [comment]
Crash log?

**Comment by Worgrick** [comment]
Dont worry too much it probably has to do with version error. I have been trying to make a nether modpack for the new version.  Your mod would be a great addition I'll send you a zip of what I have so far if you want its single player for now.

**Comment by Worgrick** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/6/20 11:22 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.class_746.method_5812()Lnet/minecraft/class_243;
	at net.minecraft.class_746.doDoubleJump(class_746.java:1749)
	at net.minecraft.class_746.handler$zdl000$doubleJumpTickMovement(class_746.java:1743)
	at net.minecraft.class_746.method_6007(class_746.java:813)
	at net.minecraft.class_1309.method_5773(class_1309.java:2216)
	at net.minecraft.class_1657.method_5773(class_1657.java:273)
	at net.minecraft.class_746.method_5773(class_746.java:201)
	at net.minecraft.class_638.method_18646(class_638.java:177)
	at net.minecraft.class_638$$Lambda$4067/257099532.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:577)
	at net.minecraft.class_638.method_18116(class_638.java:148)
	at net.minecraft.class_310.method_1574(class_310.java:1508)
	at net.minecraft.class_310.method_1523(class_310.java:978)
	at net.minecraft.class_310.method_1514(class_310.java:633)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_746.doDoubleJump(class_746.java:1749)
	at net.minecraft.class_746.handler$zdl000$doubleJumpTickMovement(class_746.java:1743)
	at net.minecraft.class_746.method_6007(class_746.java:813)
	at net.minecraft.class_1309.method_5773(class_1309.java:2216)
	at net.minecraft.class_1657.method_5773(class_1657.java:273)
	at net.minecraft.class_746.method_5773(class_746.java:201)
	at net.minecraft.class_638.method_18646(class_638.java:177)
	at net.minecraft.class_638$$Lambda$4067/257099532.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 187
	Entity Name: Worgric
	Entity's Exact location: -49.50, 73.00, -197.50
	Entity's Block location: World: (-50,73,-198), Chunk: (at 14,4,10 in -4,-13; contains blocks -64,0,-208 to -49,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:577)
	at net.minecraft.class_638.method_18116(class_638.java:148)

-- Affected level --
Details:
	All players: 1 total; [class_746['Worgric'/187, l='MpServer', x=-49.50, y=73.00, z=-197.50]]
	Chunk stats: Client Chunk Cache: 841, 462
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 5940948888331641326
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: NBT[{}]
	Level spawn location: World: (-48,67,-208), Chunk: (at 0,4,0 in -3,-13; contains blocks -48,0,-208 to -33,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 150 game time, 150 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:431)
	at net.minecraft.class_310.method_1587(class_310.java:1977)
	at net.minecraft.class_310.method_1514(class_310.java:651)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w16a
	Minecraft Version ID: 20w16a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 923274760 bytes (880 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.5.11+build.322-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cad
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa5ad
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89ad
		fabric-commands-v0: Fabric Commands (v0) 0.1.4+a2a96bf9ad
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b6ad
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.5+88afe607ad
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dad
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.3+a2a96bf9ad
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b99794ad
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd78ad
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.10+d249f7b6ad
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d6ad
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2ad
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535aad
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6ad
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7bad
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd78ad
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.2.4+eb276f9cad
		fabric-particles-v1: fabric-particles-v1 0.1.2+12a8474cad
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.10+eb276f9cad
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.12+12a8474cad
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.28+c808269fad
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60ad
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dad
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474cad
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490ad
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.1+1a47cd78ad
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.13+94c7834aad
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.3+9cd8d660ad
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba7ad
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.16-alpha.20.16.a
		org_aeonbits_owner_owner: owner 1.0.8
		walljump: Wall-Jump! 1.3.3+20w07a
	Launched Version: fabric-loader-0.8.2+build.194-20w16a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x AMD Ryzen 3 2300X Quad-Core Processor

**Comment by Worgrick** [comment]
[Nether Nomad 0.13.zip](https://github.com/genandnic/Wall-Jump/files/4587693/Nether.Nomad.0.13.zip) I hope you enjoy
