### ISSUE TITLE
Random Crash partially after world creation

### ISSUE THREAD

**Issue by Camawama** [genandnic/Wall-Jump#27]
Hey there, my game keeps crashing shortly after creating a world. It happens at random and sometimes the game crashes before I can even move in-game. Seems to work fine server-side.
[crash-2021-01-16_13.23.27-client.txt](https://github.com/genandnic/Wall-Jump/files/5825028/crash-2021-01-16_13.23.27-client.txt)

**Comment by Camawama** [comment]
13:42:05.450
net.minecraftforge.common.ForgeMod
Render thread
Preparing crash report with UUID cf8d9c0c-24d8-4a12-a301-24164d51da1f


13:42:05.453
net.minecraft.client.Minecraft
Render thread
Unreported exception thrown!
java.lang.NullPointerException
	at genandnic.walljump.proxy.ClientProxy.onClientTick(ClientProxy.java:61)
	at net.minecraftforge.eventbus.ASMEventHandler_1939_ClientProxy_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2646/561741935.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1542)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1462350864.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
